In [4]:
import numpy as np
import scipy.linalg as spla

In [3]:
A = np.array([[1,4,6], [0,2,5],[0,0,3]])
np.linalg.eigvals(A)

array([1., 2., 3.])

In [27]:
A2 = np.array([[5,0,-1],[0,1,0],[0,0,2]])

D = np.diag(np.diag(A2))
L = np.tril(A2) - D
U = A2 - L - D 

b = np.array([[2,2,4]])
print(L, D, U)
np.linalg.inv(D)@(b.T - (L + U)@np.array([[1,1,1]]).T)

[[0 0 0]
 [0 0 0]
 [0 0 0]] [[5 0 0]
 [0 1 0]
 [0 0 2]] [[ 0  0 -1]
 [ 0  0  0]
 [ 0  0  0]]


array([[0.6],
       [2. ],
       [2. ]])

In [23]:
Q,R = spla.qr(np.array([[1,2,0],[0,1,1],[1,0,1]]))

In [24]:
Q

array([[-0.70710678, -0.57735027, -0.40824829],
       [-0.        , -0.57735027,  0.81649658],
       [-0.70710678,  0.57735027,  0.40824829]])

In [25]:
R

array([[-1.41421356, -1.41421356, -0.70710678],
       [ 0.        , -1.73205081,  0.        ],
       [ 0.        ,  0.        ,  1.22474487]])

In [28]:
5**.5

2.23606797749979

In [29]:
(6**.5)/2

1.224744871391589

In [30]:
1/(np.sqrt(2))

0.7071067811865475

In [32]:
1/(np.sqrt(6))

0.4082482904638631

In [36]:
np.linalg.cholesky(np.array([[1,1,3],[0,1,0],[0,0,2]])).T

array([[1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.41421356]])